build:
  binary: task
  main: cmd/task/task.go
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
  ignore:
    - goos: darwin
      goarch: 386

archive:
  name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"

  format_overrides:
    - goos: windows
      format: zip

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

nfpm:
  vendor: Task
  homepage: https://github.com/go-task/task
  maintainer: Andrey Nering <andrey.nering@gmail.com>
  description: Simple task runner written in Go
  license: MIT
  conflicts:
    - taskwarrior
  formats:
    - deb
    - rpm

brew:
  name: go-task
  github:
    owner: go-task
    name: homebrew-tap
  commit_author:
    name: Andrey Nering
    email: andrey.nering@gmail.com
  folder: Formula
  homepage: https://github.com/go-task/task
  description: Task runner / simpler Make alternative written in Go
  conflicts:
    - taskwarrior
  install: |
    bin.install "task"
  test: |
    system "#{bin}/task", "--help"
