[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  branch = "master"
  name = "github.com/Masterminds/sprig"

[[constraint]]
  branch = "master"
  name = "github.com/imdario/mergo"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-zglob"

[[constraint]]
  branch = "master"
  name = "mvdan.cc/sh"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/radovskyb/watcher"

[[constraint]]
  branch = "master"
  name = "github.com/Masterminds/semver"
