# compiles current source code and make "task" executable available on
# $GOPATH/bin/task{.exe}
install:
  cmds:
    - go install -v ./...

lint:
  cmds:
    - golint .
    - golint ./cmd/task

test:
  deps: [install]
  cmds:
    - go test -v

# https://github.com/goreleaser/goreleaser
release:
  cmds:
    - goreleaser
